// <auto-generated />
namespace MVC_Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addtesttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtesttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201812130706595_add-test-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
